# for previewing
# baseurl: http://mxm.github.io/scalaris

# for production change baseurl to an empty string
baseurl:

repository: https://github.com/scalaris-team/scalaris
kramdown:
  toc_levels: "2,3"

# just the title, no year...
# we need the /index.html for our relative links to work properly
# (see _includes/base.html)
permalink: /blog/:title/index.html
